doctrine_migrations:
    migrations_paths:
        'eldo\MainBundle\Doctrine\Migrations': '%kernel.root_dir%/../vendor/eldolink/main-bundle/src/Doctrine/Migrations'
    storage:
        table_storage:
            table_name: 'migration_versions'