swiftmailer:
    default_mailer: sendgrid
    mailers:
        sendgrid:
            transport: "smtp"
            host:      "smtp.sendgrid.net"
            port:      "587"
            username:  "apikey"
            password:  "%env(resolve:sendgrid_api_key)%"
            spool: { type: 'memory' }