imports:
    - { resource: config.yml }

framework:
    validation:
        cache: apc

doctrine:
    orm:
#         metadata_cache_driver: apc
#         result_cache_driver: apc
#         query_cache_driver: apc
#         second_level_cache:
#             enabled:            true
#             log_enabled:        true
        metadata_cache_driver:
            type: service
            id: snc_redis.default
        result_cache_driver:
            type: service
            id: snc_redis.default
        query_cache_driver:
            type: service
            id: snc_redis.default
        second_level_cache:
            enabled:            true
            log_enabled:        true
            region_cache_driver:
                type: service
                id: snc_redis_cache_driver
            region_lock_lifetime: 60
            region_lifetime: 300
            regions:
                region_cached:
                    lifetime: 600
                    cache_driver:
                        type: service
                        id: snc_redis_cache_driver

monolog:
    handlers:
        main:
            type:         fingers_crossed
            action_level: critical
            handler:      grouped
        grouped:
            type:    group
            members: [streamed, buffered]
        streamed:
            type:  stream
            path:  "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
        buffered:
            type:    buffer
            handler: swift
        swift:
            type:       swift_mailer
            from_email: %app.admin_email%
            to_email:   %app.admin_email%
            subject:    "%app.name% : An Error Occurred!"
            level:      debug
        console:
            type:  console

parameters:
    httpProtocol: https