imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: ../../vendor/knplabs/doctrine-behaviors/config/orm-services.yml }

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
        assets_version: %assets_version%
#         assets_version_format: 'v-%%2$s/%%1$s'
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        gc_probability: 0
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Monolog Configuration
# monolog:
#     handlers:
#         main:
#             type:         fingers_crossed
#             action_level: critical
#             handler:      grouped
#         grouped:
#             type:    group
#             members: [streamed, buffered]
#         streamed:
#             type:  stream
#             path:  "%kernel.logs_dir%/%kernel.environment%.log"
#             level: debug
#         buffered:
#             type:    buffer
#             handler: swift
#         swift:
#             type:       swift_mailer
#             from_email: %app.admin_email%
#             to_email:   %app.admin_email%
#             subject:    "%app.name% : An Error Occurred!"
#             level:      debug

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    globals:
        main_app_name: %app.name%
        main_facebook_app_ip: %app.facebook.id%
        use_affiliate: %use_affiliate%

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:
           - TwigBundle
           - MopaBootstrapBundle
           - eldoPagesBundle
           - eldoToolsBundle
    #java: /usr/bin/java
    filters:
        less:
            node: /usr/bin/node
            node_paths: [/usr/lib/node_modules]
            apply_to: "\.less$"
        cssrewrite: ~
        uglifyjs2:
            bin: "/usr/bin/uglifyjs"
        uglifycss:
            bin: "/usr/bin/uglifycss"
        yui_css:
            jar: "/usr/share/yui-compressor/yui-compressor.jar"
        yui_js:
            jar: "/usr/share/yui-compressor/yui-compressor.jar"
#     workers:
#         cache_busting: ~
    variables:
        locale: "%app.locales%"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        types:
            phone_number: Misd\PhoneNumberBundle\Doctrine\DBAL\Types\PhoneNumberType
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true
        mappings:
            gedmo_loggable:
                type: annotation
                prefix: Gedmo\Loggable\Entity
                dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Loggable/Entity"
                alias: GedmoLoggable # this one is optional and will default to the name set for the mapping
                is_bundle: false

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    port:      "%mailer_port%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }
    
# LiipImagineBundle Configuration
liip_imagine:
    resolvers:
       default:
           web_path: ~ 
    loaders:
        default:
            filesystem: ~          
    filter_sets:
        thumb_16x16:
            filters:
                thumbnail: { size: [16, 16], mode: outbound, allow_upscale: true }
        thumb_196x196:
            filters:
                thumbnail: { size: [196, 196], mode: outbound, allow_upscale: true }
        thumb_152x152:
            filters:
                thumbnail: { size: [152, 152], mode: outbound, allow_upscale: true }

# MopaBootstrapBundle Configuration
mopa_bootstrap:
    form:
        checkbox_label: 'label'
        show_legend: false
        render_fieldset: false
        render_optional_text: false

# KnpSnappyBundle Configuration
knp_snappy:
    pdf:
        enabled:    true
        binary:     %kernel.root_dir%/../vendor/h4cc/wkhtmltopdf-amd64/bin/wkhtmltopdf-amd64
        options:    []
    image:
        enabled:    true
        binary:     %kernel.root_dir%/../vendor/h4cc/wkhtmltoimage-amd64/bin/wkhtmltoimage-amd64
        options:    []

# FOSUserBundle Configuration
fos_user:
    db_driver: orm
    firewall_name: main
    user_class: eldo\MainBundle\Entity\Customer

# JMSTranslationBundle Configuration
jms_translation:
    configs:
        app:
            dirs: [%kernel.root_dir%, %kernel.root_dir%/../src]
            output_dir: %kernel.root_dir%/Resources/translations
            ignored_domains: [routes]
            excluded_names: ["*TestCase.php", "*Test.php"]
            excluded_dirs: [cache, data, logs]

# JMSI18nRoutingBundle Configuration
jms_i18n_routing:
    default_locale: "%locale%"
    locales: "%app.locales%"
    strategy: prefix_except_default
    
# DoctrineCacheBundle Configuration
doctrine_cache:
    providers:
        memcached_cache:
            namespace: memcached_ns
            type: memcached

# MobileDetectBundle Configuration
mobile_detect:
    redirect:
        mobile: ~
        tablet: ~
    switch_device_view: ~

# Stof\DoctrineExtensionBundle configuration
stof_doctrine_extensions:
    orm:
        default:
            sluggable: true
            loggable: true

# KnpGaufretteBundle configuration
knp_gaufrette:
    stream_wrapper: ~

    adapters:
        media_local_adapter:
            local:
                directory: %kernel.root_dir%/../web/uploads/files
        media_database_adapter:
            doctrine_dbal:
                connection_name: default
                table: eldo_media
                columns:
                    key: file_name
                    content: file_data
                    mtime: uploadedat
                    checksum: file_checksum

    filesystems:
        media_fs:
            adapter:    media_local_adapter
        database_fs:
            adapter:    media_database_adapter

# VichUploaderBundle configuration
vich_uploader:
    db_driver: orm
    storage:   gaufrette

    mappings:
        file:
            uri_prefix:         /uploads/files
            upload_destination: media_fs
#             upload_destination: database_fs
            namer:              vich_uploader.namer_uniqid

# EndroidGoogleBundle Configuration
endroid_google_analytics:
    trackers:
        default: UA-59826262-4
        
# CravlerMaxmindGeoIPBundle Configuration
cravler_max_mind_geo_ip:
#    path: '%kernel.root_dir%/Resources/MaxMind'
    path: '/usr/local/share/GeoIP'
    db:
        country: 'GeoIP2-Country.mmdb'
        city: 'GeoLite2-City.mmdb'
        connection_type: 'GeoIP2-Connection-Type.mmdb'
        domain: 'GeoIP2-Domain.mmdb'
        isp: 'GeoIP2-ISP.mmdb'
    source:
        country: ~
        city: ~
        connection_type: ~
        domain: ~
        isp: ~
        
# KachkaevAssetsVersionBundle Configuration
kachkaev_assets_version: ~

# AcceleratorCacheBundle Configuration
accelerator_cache:
    mode: curl
    host: https://www.eldoslim.com
    web_dir: %kernel.root_dir%/../web

# eldoMainBundle Configuration
eldo_main:
    sendgrid:
        username:   %sendgrid_username%
        password:   %sendgrid_password%
    api:
        url:        %api_url%
        version:    %api_version%
    default_offer:  %default_offer%

parameters:
    httpProtocol: http