imports:
    - { resource: config.yml }

framework:
    assets:
        version: "%assets_version%"
        base_urls: "%app.cdn_url%"

doctrine:
    orm:
        metadata_cache_driver:
            type: service
            id: snc_redis.default
        result_cache_driver:
            type: service
            id: snc_redis.default
        query_cache_driver:
            type: service
            id: snc_redis.default
        second_level_cache:
            enabled:            true
            log_enabled:        true
            region_cache_driver:
                type: service
                id: snc_redis_cache_driver
            region_lock_lifetime: 60
            region_lifetime: 300
            regions:
                region_cached:
                    lifetime: 600
                    cache_driver:
                        type: service
                        id: snc_redis_cache_driver

monolog:
    handlers:
        main:
            type:         fingers_crossed
            action_level: critical
            handler:      grouped
        grouped:
            type:    group
            members: [streamed, buffered]
        streamed:
            type: rotating_file
            max_files: 10
            path:  "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
        buffered:
            type:    buffer
            handler: swift
        swift:
            type:       swift_mailer
            from_email: "%app.admin_email%"
            to_email:   "%app.admin_email%"
            subject:    "%app.name% : An Error Occurred!"
            level:      debug
        console:
            type:  console

# EkinoNewRelicBundle Configuration
ekino_new_relic:
    enabled: true
    application_name: "%app.name%"
    deployment_names: ~
    api_key: "%newrelic_api_key%"
    xmit: false
    logging: true
    instrument: false
    log_exceptions: true
    log_commands: true
    using_symfony_cache: false
    transaction_naming: route
    transaction_naming_service: ~
    ignored_routes: []                    # No transaction recorded for this routes
    ignored_paths: []                     # No transaction recorded for this paths
    ignored_commands: []                  # No transaction recorded for this commands (background tasks)
