imports:
    - { resource: config.yml }

framework:
    assets:
        version: "%assets_version%"
        base_urls: "%app.cdn_url%"

monolog:
    handlers:
        main:
            type:         fingers_crossed
            action_level: critical
            handler:      grouped
        grouped:
            type:    group
            members: [streamed, buffered]
        streamed:
            type: rotating_file
            max_files: 10
            path:  "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
        buffered:
            type:    buffer
            handler: swift
        swift:
            type:       swift_mailer
            from_email: "%app.admin_email%"
            to_email:   "%app.admin_email%"
            subject:    "%app.name% : An Error Occurred!"
            level:      debug
        console:
            type:  console

# EkinoNewRelicBundle Configuration
ekino_new_relic:
    enabled: true
    application_name: "%app.name%"
    deployment_names: ~
    api_key: "%newrelic_api_key%"
    xmit: false
    logging: true
    instrument: false
    log_exceptions: true
    log_commands: true
    using_symfony_cache: false
    transaction_naming: route
    transaction_naming_service: ~
    ignored_routes: []                    # No transaction recorded for this routes
    ignored_paths: []                     # No transaction recorded for this paths
    ignored_commands: []                  # No transaction recorded for this commands (background tasks)

# DoctrineBundle Configuration
doctrine:
    orm:
        entity_managers:
            default:
                query_cache_driver:
                    type: service
                    id: 'doctrine.cache.memcached'
                result_cache_driver:
                    type: service
                    id: 'doctrine.cache.memcached'
                metadata_cache_driver:
                    type: service
                    id: 'doctrine.cache.memcached'
# doctrine:
#     orm:
#         second_level_cache:
#             enabled:            true
#             log_enabled:        true
#             region_cache_driver:
#                 type: service
#                 id: snc_redis_cache_driver
#             region_lifetime: 3600
#             regions:
#                 region_cached:
#                     lifetime: 60
#                     cache_driver:
#                         type: service
#                         id: snc_redis_cache_driver

# DoctrineCacheBundle Configuration
doctrine_cache:
    providers:
        memcached_cache:
            namespace: memcached_ns
            type: memcached

#SncRedisBundle configuration
# snc_redis:
#     doctrine:
#         metadata_cache:
#             client: default
#             entity_manager: default
#             namespace: 'dmc:'
#         result_cache:
#             client: default
#             entity_manager: default
#             namespace: 'drc:'
#         query_cache:
#             client: default
#             entity_manager: default
#             namespace: 'dqc:'
#         second_level_cache:
#             client: default
#             entity_manager: default
#             namespace: 'dslc:'