# app/config/routing.yml
_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"
    schemes:  [%httpProtocol%]

slimdoo_gateway:
    pattern:  /g
    defaults: { _controller: eldoPagesBundle:Page:gateway }
    requirements:
        methods:  GET|POST
    schemes:  [%httpProtocol%]

slimdoo_home:
    pattern:  /
    defaults: { _controller: eldoPagesBundle:Page:home }
    requirements:
        methods:  GET|POST
    schemes:  [%httpProtocol%]

slimdoo_pdv1:
    pattern:  /pdv/1
    defaults: { _controller: eldoPagesBundle:Page:pdv1 }
    requirements:
        methods:  GET|POST
    schemes:  [%httpProtocol%]

slimdoo_pdv2:
    pattern:  /pdv/2
    defaults: { _controller: eldoPagesBundle:Page:pdv2 }
    requirements:
        methods:  GET|POST
    schemes:  [%httpProtocol%]

slimdoo_pdv3:
    pattern:  /pdv/3
    defaults: { _controller: eldoPagesBundle:Page:pdv3 }
    requirements:
        methods:  GET
    schemes:  [%httpProtocol%]

slimdoo_gifts:
    pattern:  /gifts
    defaults: { _controller: eldoPagesBundle:Page:gifts }
    requirements:
        _method:  GET|POST
    schemes:  [%httpProtocol%]

slimdoo_internetplus_modal:
    pattern:  /internetplusModal
    defaults: { _controller: eldoPagesBundle:Page:internetplusModal }
    requirements:
        methods:  POST
    schemes:  [%httpProtocol%]

slimdoo_internetplus:
    pattern:  /internetplus
    defaults: { _controller: eldoPagesBundle:Page:internetplus }
    requirements:
        methods:  GET|POST
    schemes:  [%httpProtocol%]

slimdoo_audiotel_home:
    pattern:  /audiotel
    defaults: { _controller: eldoPagesBundle:Audiotel:home }
    requirements:
        methods:  GET
    schemes:  [%httpProtocol%]

slimdoo_sms_home:
    pattern:  /sms
    defaults: { _controller: eldoPagesBundle:Sms:home }
    requirements:
        methods:  GET
    schemes:  [%httpProtocol%]

slimdoo_check_email:
    pattern:  /check_email
    defaults: { _controller: eldoPagesBundle:Page:checkEmail }
    requirements:
        methods:  POST
    schemes:  [%httpProtocol%]

content_show:
    pattern:  /content_show/{identifier}
    defaults: { _controller: eldoPagesBundle:Content:content }
    requirements:
        methods:  GET|POST
    schemes:  [%httpProtocol%]

content_show_image:
    pattern:  /content/img/{identifier}
    defaults: { _controller: eldoPagesBundle:Content:contentImage }
    requirements:
        methods:  GET|POST
    schemes:  [%httpProtocol%]

example_home:
    pattern:  /example/
    defaults: { _controller: eldoPagesBundle:Example:home }
    requirements:
        methods:  GET|POST
    schemes:  [%httpProtocol%]

check_email:
    pattern:  /check_email
    defaults: { _controller: eldoToolsBundle:Api:checkEmail }
    requirements:
        methods:  POST
    schemes:  [%httpProtocol%]

eldo_tools:
    resource: "@eldoToolsBundle/Controller/" 
    type: annotation
    prefix:   /
    schemes:  [%httpProtocol%]