# app/config/routing.yml
_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"
    schemes:  [%httpProtocol%]

eldoMainBundle: 
    resource: "@eldoMainBundle/Controller/"
    type: annotation
    prefix:   /

slimdoo_portal_index:
    path:  /
    defaults: { _controller: eldoPagesBundle:Portal:index }
    methods:  [GET]
    schemes:  [%httpProtocol%]

slimdoo_portal_products:
    path:  /products
    defaults: { _controller: eldoPagesBundle:Portal:products }
    methods:  [GET]
    schemes:  [%httpProtocol%]

slimdoo_portal_product_show:
    path:  /product/{id}/{slug}
    defaults: { _controller: eldoPagesBundle:Portal:productShow }
    methods:  [GET]
    schemes:  [%httpProtocol%]
    requirements:
        id: '\d+'

slimdoo_portal_ajax_modal:
    path:  /modal
    defaults: { _controller: eldoPagesBundle:Portal:ajaxModal }
    methods:  [POST]
    schemes:  [%httpProtocol%]

slimdoo_portal_tips:
    path:  /tips
    defaults: { _controller: eldoPagesBundle:Portal:tips }
    methods:  [GET]
    schemes:  [%httpProtocol%]

slimdoo_portal_tip_show:
    path:  /{id}/{slug}
    defaults: { _controller: eldoPagesBundle:Portal:tipShow }
    methods:  [GET]
    schemes:  [%httpProtocol%]
    requirements:
        id: '\d+'
        
slimdoo_portal_testimonials:
    path:  /testimonials
    defaults: { _controller: eldoPagesBundle:Portal:testimonials, page: 1 }
    methods:  [GET]
    schemes:  [%httpProtocol%]

slimdoo_portal_testimonials_page:
    path:  /testimonials/page/{page}
    defaults: { _controller: eldoPagesBundle:Portal:testimonials }
    methods:  [GET]
    schemes:  [%httpProtocol%]
    requirements:
        page: '\d+'

slimdoo_portal_confirm:
    path:  /confirm/{identifier}/{token}
    defaults: { _controller: eldoPagesBundle:Portal:confirm }
    methods:  [GET, POST]
    schemes:  [%httpProtocol%]

slimdoo_portal_result:
    path:  /result/{identifier}/{token}
    defaults: { _controller: eldoPagesBundle:Portal:result }
    methods:  [GET, POST]
    schemes:  [%httpProtocol%]

slimdoo_portal_tool:
    path:  /tool/{identifier}
    defaults: { _controller: eldoPagesBundle:Portal:tool }
    methods:  [GET, POST]
    schemes:  [%httpProtocol%]

slimdoo_portal_email_instructions:
    path:  /email_instructions/{identifier}
    defaults: { _controller: eldoPagesBundle:Portal:emailInstructions }
    methods:  [GET, POST]
    schemes:  [%httpProtocol%]

slimdoo_home:
    path:  /slimdoo
    defaults: { _controller: eldoPagesBundle:Page:home }
    methods:  [GET, POST]
    schemes:  [%httpProtocol%]

slimdoo_pdv1:
    path:  /pdv/1
    defaults: { _controller: eldoPagesBundle:Page:pdv1 }
    methods:  [GET, POST]
    schemes:  [%httpProtocol%]

slimdoo_pdv2:
    path:  /pdv/2
    defaults: { _controller: eldoPagesBundle:Page:pdv2 }
    methods:  [GET, POST]
    schemes:  [%httpProtocol%]

slimdoo_pdv3:
    path:  /pdv/3
    defaults: { _controller: eldoPagesBundle:Page:pdv3 }
    methods:  [GET, POST]
    schemes:  [%httpProtocol%]

slimdoo_pdv4:
    path:  /pdv/4
    defaults: { _controller: eldoPagesBundle:Page:pdv4 }
    methods:  [GET, POST]
    schemes:  [%httpProtocol%]

slimdoo_pdv5:
    path:  /pdv/5
    defaults: { _controller: eldoPagesBundle:Page:pdv5 }
    methods:  [GET, POST]
    schemes:  [%httpProtocol%]

slimdoo_pdv6:
    path:  /pdv/6
    defaults: { _controller: eldoPagesBundle:Page:pdv6 }
    methods:  [GET, POST]
    schemes:  [%httpProtocol%]

slimdoo_pdv7:
    path:  /pdv/7
    defaults: { _controller: eldoPagesBundle:Page:pdv7 }
    methods:  [GET, POST]
    schemes:  [%httpProtocol%]

slimdoo_pdv8:
    path:  /pdv/8
    defaults: { _controller: eldoPagesBundle:Page:pdv8 }
    methods:  [GET, POST]
    schemes:  [%httpProtocol%]

slimdoo_pdv9:
    path:  /pdv/9
    defaults: { _controller: eldoPagesBundle:Page:pdv9 }
    methods:  [GET, POST]
    schemes:  [%httpProtocol%]

slimdoo_pdv10:
    path:  /pdv/10
    defaults: { _controller: eldoPagesBundle:Page:pdv10 }
    methods:  [GET, POST]
    schemes:  [%httpProtocol%]

slimdoo_pdv11:
    path:  /pdv/11
    defaults: { _controller: eldoPagesBundle:Page:pdv11 }
    methods:  [GET, POST]
    schemes:  [%httpProtocol%]

slimdoo_pdv14:
    path:  /pdv/14
    defaults: { _controller: eldoPagesBundle:Page:pdv14 }
    methods:  [GET, POST]
    schemes:  [%httpProtocol%]

slimdoo_pdv15:
    path:  /pdv/15
    defaults: { _controller: eldoPagesBundle:Page:pdv15 }
    methods:  [GET, POST]
    schemes:  [%httpProtocol%]

slimdoo_pdv16:
    path:  /pdv/16
    defaults: { _controller: eldoPagesBundle:Page:pdv16 }
    methods:  [GET, POST]
    schemes:  [%httpProtocol%]

slimdoo_pdv17:
    path:  /pdv/17
    defaults: { _controller: eldoPagesBundle:Page:pdv17 }
    methods:  [GET, POST]
    schemes:  [%httpProtocol%]

slimdoo_pdv18:
    path:  /pdv/18
    defaults: { _controller: eldoPagesBundle:Page:pdv18 }
    methods:  [GET, POST]
    schemes:  [%httpProtocol%]

slimdoo_pdv19:
    path:  /pdv/19
    defaults: { _controller: eldoPagesBundle:Page:pdv19 }
    methods:  [GET, POST]
    schemes:  [%httpProtocol%]

slimdoo_pdv20:
    path:  /pdv/20
    defaults: { _controller: eldoPagesBundle:Page:pdv20 }
    methods:  [GET, POST]
    schemes:  [%httpProtocol%]

slimdoo_pdv21:
    path:  /pdv/21
    defaults: { _controller: eldoPagesBundle:Page:pdv21 }
    methods:  [GET, POST]
    schemes:  [%httpProtocol%]

slimdoo_pdv22:
    path:  /pdv/22
    defaults: { _controller: eldoPagesBundle:Page:pdv22 }
    methods:  [GET, POST]
    schemes:  [%httpProtocol%]

slimdoo_pdv23:
    path:  /pdv/23
    defaults: { _controller: eldoPagesBundle:Page:pdv23 }
    methods:  [GET, POST]
    schemes:  [%httpProtocol%]

slimdoo_pdv24:
    path:  /pdv/24
    defaults: { _controller: eldoPagesBundle:Page:pdv24 }
    methods:  [GET, POST]
    schemes:  [%httpProtocol%]

slimdoo_pdv25:
    path:  /pdv/25
    defaults: { _controller: eldoPagesBundle:Page:pdv25 }
    methods:  [GET, POST]
    schemes:  [%httpProtocol%]

slimdoo_pdv26:
    path:  /pdv/26
    defaults: { _controller: eldoPagesBundle:Page:pdv26 }
    methods:  [GET, POST]
    schemes:  [%httpProtocol%]

slimdoo_pdv27:
    path:  /pdv/27
    defaults: { _controller: eldoPagesBundle:Page:pdv27 }
    methods:  [GET, POST]
    schemes:  [%httpProtocol%]

slimdoo_pdv28:
    path:  /pdv/28
    defaults: { _controller: eldoPagesBundle:Page:pdv28 }
    methods:  [GET, POST]
    schemes:  [%httpProtocol%]

slimdoo_pdv29:
    path:  /pdv/29
    defaults: { _controller: eldoPagesBundle:Page:pdv29 }
    methods:  [GET, POST]
    schemes:  [%httpProtocol%]

slimdoo_pdv30:
    path:  /pdv/30
    defaults: { _controller: eldoPagesBundle:Page:pdv30 }
    methods:  [GET, POST]
    schemes:  [%httpProtocol%]

slimdoo_pdv31:
    path:  /pdv/31
    defaults: { _controller: eldoPagesBundle:Page:pdv31 }
    methods:  [GET]
    schemes:  [%httpProtocol%]

slimdoo_pdv32:
    path:  /pdv/32
    defaults: { _controller: eldoPagesBundle:Page:pdv32 }
    methods:  [GET]
    schemes:  [%httpProtocol%]

slimdoo_pdv33:
    path:  /pdv/33
    defaults: { _controller: eldoPagesBundle:Page:pdv33 }
    methods:  [GET]
    schemes:  [%httpProtocol%]

slimdoo_pdv34:
    path:  /pdv/34
    defaults: { _controller: eldoPagesBundle:Page:pdv34 }
    methods:  [GET]
    schemes:  [%httpProtocol%]

slimdoo_pdv35:
    path:  /pdv/35
    defaults: { _controller: eldoPagesBundle:Page:pdv35 }
    methods:  [GET]
    schemes:  [%httpProtocol%]

slimdoo_pdv36:
    path:  /pdv/36
    defaults: { _controller: eldoPagesBundle:Page:pdv36 }
    methods:  [GET]
    schemes:  [%httpProtocol%]

slimdoo_pdv37:
    path:  /pdv/37
    defaults: { _controller: eldoPagesBundle:Page:pdv37 }
    methods:  [GET]
    schemes:  [%httpProtocol%]

slimdoo_gifts:
    path:  /gifts
    defaults: { _controller: eldoPagesBundle:Page:gifts }
    methods:  [GET, POST]
    schemes:  [%httpProtocol%]

slimdoo_internetplus_modal:
    path:  /internetplusModal
    defaults: { _controller: eldoPagesBundle:Page:internetplusModal }
    methods:  [POST]
    schemes:  [%httpProtocol%]

slimdoo_internetplus:
    path:  /internetplus
    defaults: { _controller: eldoPagesBundle:Page:internetplus }
    methods:  [GET, POST]
    schemes:  [%httpProtocol%]

slimdoo_audiotel_home:
    path:  /audiotel
    defaults: { _controller: eldoPagesBundle:Audiotel:home }
    methods:  [GET]
    schemes:  [%httpProtocol%]

slimdoo_sms_home:
    path:  /sms
    defaults: { _controller: eldoPagesBundle:Sms:home }
    methods:  [GET]
    schemes:  [%httpProtocol%]

example_home:
    path:  /example/
    defaults: { _controller: eldoPagesBundle:Example:home }
    methods:  [GET, POST]
    schemes:  [%httpProtocol%]

slimdoo_gateway:
    path:  /g
    defaults: { _controller: eldoPagesBundle:Page:gateway }
    methods:  [GET, POST]
    schemes:  [%httpProtocol%]

_slimdoo_track:
    path:  /track
    defaults: { _controller: eldoPagesBundle:Page:track }
    methods:  [GET]
    schemes:  [%httpProtocol%]

check_email:
    path:  /check_email
    defaults: { _controller: eldoToolsBundle:Api:checkEmail }
    methods:  [POST]
    schemes:  [%httpProtocol%]

testimonial_show:
    path:  /testimonial/{product}
    defaults: { _controller: eldoPagesBundle:Testimonial:show, page: 1 }
    methods:  [GET, POST]
    schemes:  [%httpProtocol%]

testimonial_show_product_page:
    path:  /testimonial/{product}/page/{page}
    defaults: { _controller: eldoPagesBundle:Testimonial:show }
    methods:  [GET, POST]
    schemes:  [%httpProtocol%]
    requirements:
        page: '\d+'

testimonial_show_page:
    path:  /testimonial/page/{page}
    defaults: { _controller: eldoPagesBundle:Testimonial:show }
    methods:  [GET, POST]
    schemes:  [%httpProtocol%]
    requirements:
        page: '\d+'

video_show:
    path:  /video
    defaults: { _controller: eldoPagesBundle:Content:video }
    methods:  [POST]
    schemes:  [%httpProtocol%]

content_show_image:
    path:  /content/img/{identifier}
    defaults: { _controller: eldoPagesBundle:Content:contentImage }
    methods:  [GET, POST]
    schemes:  [%httpProtocol%]

content_show_pdf:
    path:  /content/pdf/{identifier}
    defaults: { _controller: eldoPagesBundle:Content:contentPdf }
    methods:  [GET, POST]
    schemes:  [%httpProtocol%]

content_show:
    path:  /content_show/{identifier}
    defaults: { _controller: eldoPagesBundle:Content:content }
    methods:  [GET, POST]
    schemes:  [%httpProtocol%]

slimdoo_ajax_cart:
    path:  /getCart
    defaults: { _controller: eldoPagesBundle:Page:ajaxCart }
    methods:  [POST]
    schemes:  [%httpProtocol%]

slimdoo_ajax_addtocart:
    path:  /addToCart
    defaults: { _controller: eldoPagesBundle:Page:ajaxAddToCart }
    methods:  [POST]
    schemes:  [%httpProtocol%]

slimdoo_ajax_updatecart:
    path:  /updateCart
    defaults: { _controller: eldoPagesBundle:Page:ajaxUpdateCart }
    methods:  [POST]
    schemes:  [%httpProtocol%]

slimdoo_ajax_catcher:
    path:  /catcher
    defaults: { _controller: eldoPagesBundle:Page:ajaxCatcher }
    methods:  [POST]
    schemes:  [%httpProtocol%]

slimdoo_ajax_optin:
    path:  /optin
    defaults: { _controller: eldoPagesBundle:Page:ajaxOptin }
    methods:  [POST]
    schemes:  [%httpProtocol%]

slimdoo_ajax_terms:
    path:  /terms
    defaults: { _controller: eldoPagesBundle:Page:ajaxTerms }
    methods:  [POST]
    schemes:  [%httpProtocol%]

slimdoo_ajax_notify:
    path:  /notify
    defaults: { _controller: eldoPagesBundle:Page:ajaxNotify }
    methods:  [POST]
    schemes:  [%httpProtocol%]

eldo_tools:
    resource: "@eldoToolsBundle/Controller/" 
    type: annotation
    prefix:   /
    schemes:  [%httpProtocol%]