# app/config/security.yml
security:
    encoders:
        eldo\MainBundle\Entity\Customer:
            algorithm: sha512
            iterations: 9616

    providers:
         app_user_customer:
            entity:
                class: eldo\MainBundle\Entity\Customer

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
            context:  eldo

        main:
            anonymous: ~
            logout_on_user_change: true
