# app/config/security.yml
security:
    encoders:
        FOS\UserBundle\Model\UserInterface:
            algorithm: sha512
            iterations: 9616

    providers:
         fos_userbundle:
             id: fos_user.user_provider.username

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
            context:  eldo

        main:
            anonymous: ~
            logout_on_user_change: true
