doctrine:
    orm:
        metadata_cache_driver:
            type: pool
            pool: doctrine.cache_pool
        query_cache_driver:
            type: pool
            pool: doctrine.cache_pool
        result_cache_driver:
            type: pool
            pool: doctrine.cache_pool

framework:
    cache:
        pools:
            doctrine.cache_pool:
                adapter: cache.app
