ekino_new_relic:
    enabled: true
    application_name: '%env(resolve:app_name)%'
    deployment_names: ~
    api_key: '%env(resolve:NEWRELIC_API_KEY)%'
    xmit: false
    logging: true
    instrument: false
    deprecations: false