liip_imagine:
    resolvers:
        resolver_s3_medias:
            aws_s3:
                client_config:
                    credentials:
                        key: '%env(resolve:amazon_s3_key)%'
                        secret: '%env(resolve:amazon_s3_secret)%'
                    region: '%env(resolve:amazon_s3_region)%'
                    version: 'latest'
                bucket: '%env(resolve:amazon_s3_medias_bucket_name)%cache'