monolog:
    handlers:
        main:
            type:         fingers_crossed
            action_level: critical
            handler:      grouped
        grouped:
            type:    group
            members: [streamed, buffered]
        streamed:
            type: rotating_file
            max_files: 10
            path:  "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
        buffered:
            type:    buffer
            handler: swift
        swift:
            type:       swift_mailer
            from_email: '%env(resolve:app_admin_email)%'
            to_email:   '%env(resolve:app_admin_email)%'
            subject:    "%env(resolve:app_name)% : An Error Occurred!"
            level:      debug
        console:
            type:  console
